services:
  init-permissions:
    image: docker.io/library/alpine
    user: "root"
    volumes:
      - shared-download:/data
    command: chown -R 1000:1000 /data
  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
  yt-dlp-api:
    build: .
    command: gunicorn -w 4 --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker app.main:app
    volumes:
      - shared-download:/app/downloads:ro
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - rabbitmq
      - worker
    restart: unless-stopped
  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.workers.worker.celery worker --loglevel=info
    volumes:
      - shared-download:/app/downloads
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      - rabbitmq
    restart: unless-stopped
  nginx:
    image: docker.io/library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    depends_on:
      - rabbitmq
      - worker
      - yt-dlp-api
    restart: always
volumes:
  shared-download:
