server {
  listen 80;

  add_header Access-Control-Allow-Origin '*' always;
  add_header Access-Control-Allow-Headers '*';
  add_header Access-Control-Allow-Methods '*';
  if ($request_method = 'OPTIONS') {
    return 204;
  }

  proxy_hide_header Access-Control-Allow-Origin;
  proxy_buffer_size 4k;
  proxy_buffers 8 4k;

  location / {
    proxy_pass http://yt-dlp-api:8000;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;
  }
}
