import os
from pathlib import Path

import yt_dlp
from celery import Celery
from yt_dlp.utils import DownloadError
from playwright.sync_api import sync_playwright

DOWNLOAD_DIR = Path('/app/downloads/')
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

celery = Celery(
    "worker",
    broker="amqp://guest:guest@rabbitmq:5672//",
    backend="rpc://",
)

def get_cookie_from_playwright():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
        page = context.new_page()

        page.goto("https://www.youtube.com", wait_until="domcontentloaded")
        page.wait_for_load_state("networkidle")
        
        cookies = context.cookies()
        cookie_file = '/tmp/cookies.txt'
        _write_netscape_cookiefile(cookies, cookie_file)
        browser.close()

def _write_netscape_cookiefile(cookies: list[dict], path: str) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Playwright + yt-dlp pipeline. Do not edit.",
        "",
    ]

    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue

        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        cookie_path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"

        expires = c.get("expires", -1)
        expires = 0 if expires is None or expires < 0 else int(expires)

        name = c.get("name", "")
        value = c.get("value", "")

        domain_field = f"#HttpOnly_{domain}" if c.get("httpOnly") else domain

        lines.append(
            "\t".join(
                [domain_field, include_subdomains, cookie_path, secure, str(expires), name, value]
            )
        )

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")

@celery.task
def download_video_task(url: str, job_id: str) -> str:
    #cookie_content = get_cookie_from_playwright()
    cookie_file = '/tmp/cookies.txt'

    filepath = os.path.join(DOWNLOAD_DIR, f"{job_id}.mp4")
    clients = ["default", "mweb", "tv"]
    for client in clients:
        youtube_args: dict[str, list[str]] = {"player_client": [client]}
        extractor_args = {"youtube": youtube_args}

        ydl_opts = {
            #'cookiefile': cookie_file,
            'extractor_args': extractor_args,
            "outtmpl": filepath,
            "format": "best",
            'js_runtimes': {
                'deno': {
                    'path': '/home/appuser/.deno/bin/deno'
                },
            },
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
        except DownloadError as e:
            continue
        except Exception as e:
            log_path = os.path.join(DOWNLOAD_DIR, f"{job_id}.log")
            with open(log_path, 'w') as f:
                f.write(f'{str(e)}\n')

        return filepath
