name: Trigger auto deployment for peterli-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/peterli-service-AutoDeployTrigger-19f310da-d399-4839-a871-dcc5761e7354.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PETERLISERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PETERLISERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PETERLISERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.PETERLISERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PETERLISERVICE_REGISTRY_PASSWORD }}
          containerAppName: peterli-service
          resourceGroup: peterli123
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


