name: API Tests

on: [ push, pull_request ]

jobs:
  up-and-running:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Building the Docker Compose
        run: docker compose build
      - name: Running the Docker Compose
        run: docker compose up -d
      - name: Run tests
        run: |
          docker compose exec yt-dlp-api pip install -r requirements-dev.txt
          docker compose exec yt-dlp-api python -m pytest -s ./app/tests
